FROM 127.0.0.1:10000/helena-job-base:1.0.0

ENV PROJECT_ENV test
ENV DB_HOST 127.0.0.1
ENV DB_PORT 3306
ENV DB_NAME demo
ENV DB_USER root
ENV DB_PASS root
ENV PROJECT_GROUP console

RUN mkdir -p /data/www/storage/${PROJECT_ENV}-logs \
	&& mkdir -p /etc/supervisor

COPY ./runtime/pack-dict /data/www
COPY ./runtime/supervisor-default.conf /etc/supervisor/conf.d/supervisor-default.conf
COPY ./runtime/.keep /data/www/storage/${PROJECT_ENV}-logs/.keep
COPY ./tools/composer.phar /usr/bin/composer
COPY ./tools/project-init.sh /opt/project.sh
COPY ./tools/register-cron.php /opt/RegisterCron.php


RUN echo "user=www" >> /etc/supervisor/supervisord.conf \
	&& chmod +x /opt/project.sh \
    #&& /bin/bash /opt/project.sh \
	&& chmod -R 777 /data/www

CMD ["supervisord", "-n"]
